@baseUrl = http://localhost:8081/api

###
POST http://localhost:8080/realms/library-realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=library-client&client_secret=wr1KEOx6JiBLngtW13XcwDerF402RWo3&grant_type=password&username=testuser&password=1234567890

> {%
    client.global.set("token", response.body.access_token);
%}

###
GET {{baseUrl}}/books
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/books/1
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/books
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "1984",
  "author": "George Orwell",
  "availableCopies": 5
}

###
PUT {{baseUrl}}/books/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "1984",
  "author": "George Orwell",
  "availableCopies": 4
}

###
DELETE {{baseUrl}}/books/1
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/borrow/1
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/borrow/return/1
Authorization: Bearer {{token}}